### ISSUE TITLE
error: self-signed certificate RDS

### ISSUE THREAD

**Issue by GitToby** [dbcodeio/public#474]
Trying to connect to an RDS through SSH, the check box `SSL automatically configured for this host.` is automatically checked. Error is posted:

```
error: self-signed certificate
```

This works with other DB browsers with the exact same configs, any ponters to change?

**Comment by GitToby** [comment]
Where does it download the certs to? I can check they're being downloaded correctly

re config, we're using a pretty vanilla `aurora-mysql` setup with nothing changed in the SSL confs. We have it in a private subnet and are using a jump host for access, hence the SSH. No shared compute/API or proxt resources associated or being used.

On the ssh point it could be, I haven't done any poking about on our jump host but can check for things that exist on that if needed. 


---

**maybe off topic, ignore if not helpful**

I'm not an SSH guru, but we do leverage SSH tunnels for local work. I'd run `ssh client-qa-tunnel &` before running a Python script to access a specific db "locally". The configs from the `.ssh/config` file appear in the "tunnels" window as `clinet-*` no matter the name, below is an example file I use:

```
Host client-*
    User ec2-user
    IdentityFile ~/.ssh/id_ed25519
    IdentitiesOnly yes

Host client-env
    HostName 123.123.123.123

Host client-env-tunnel
    HostName 123.123.123.123
    SessionType none
    LocalForward 3306 my-rds-url-from-console.eu-west-2.rds.amazonaws.com:3306
```

Ideally, the `client-env` is the tunnel I want to use right? Currently I've replicated this as 
the below during testing (redacted, but its the same settings as the ssh config):

<img width="958" alt="Image" src="https://github.com/user-attachments/assets/fdab681c-b04b-4038-8422-3fd46099129c" />

**Comment by mikeburgh** [comment]
Yeah, so there were a few issues here: 

* I should have been ignoring the Host configs with \* That's now in place
* Trying to get all the details correctly out of the ssh.config was going to be impossible, so now configs that are discovered, will use the native ssh client. To answer your question, yes the client-env is theone to use.
* The SSL was more tricky, each driver needed to be tweaked a little bit to sort out the correct host name to use when validating the certificate. That's been fixed now, so should solve the certificate issue.<br><br>Give version 1.12.3 which has just been released a try and let me know how you go

**Comment by GitToby** [comment]
Thanks for the update, bumped version to 1.12.4

Looks like 2 errors are depending on the route:

## SSH Via ssh.config
- Still showing `client-*` for all config defined settings in the tunnels pane

<img width="1176" alt="Image" src="https://github.com/user-attachments/assets/243017a6-a528-48c2-a1b8-b644993ddfc4" />

- `Error starting SSH tunnel client-*: SSH process exited with code 255` when trying to connect to the MySQL instance.

## Connecting via a DBCode-defined tunnel
The tunnel has the same settings as the ssh.config
```
Error connecting to Hippo QA, error: certificate identify Error: Hostname/IP does not match certificate's altnames: Host: localhost. is not in the cert's altnames: DNS:[REDACTED].rds.amazonaws.com, DNS:[REDACTED].rds.amazonaws.com, DNS:[REDACTED].rds.amazonaws.com
```

**Comment by mikeburgh** [comment]
Sorted out the -* problem, it was not showing up for me as my *'s were defined after the proper name..  But fixed now.

The SSL problem was a bit more complex, the driver was not correctly supporting the node TLS, but in debugging that, found a bigger issue in the driver: https://github.com/mariadb-corporation/mariadb-connector-nodejs/issues/313 

I have worked around it for now, so should work fine now (and correctly validate the cert when connecting over a tunnel). 

Let me know how it goes for you in 1.12.5 which has just been released.

**Comment by GitToby** [comment]
Looks like it's working as expected now! all ssh tunnels are well named and the connection is working - much appreciated!
