### ISSUE TITLE
Cannot connect to large MySQL databases

### ISSUE THREAD

**Issue by raphael-yapla** [dbcodeio/public#862]
## Bug Description
First off, thank you for the great extension!

We have *very* large production databases, to the tune of more than ~300,000 tables per db. When trying to connect to a database that large, the connection always fail and prompts the following error:

> "Error getting databases for connection x, error: Query execution was interrupted, maximum statement execution time exceeded"

I also tried connecting directly using the "Open table" command but it fails as well

## Repro steps
1. Add a connection to a large database (more than 300k tables)
2. Click on the connection
3. Watch it fail

## Expected Behavior
I would expect to be able to connect to the database normally, I don't want to list the tables but I'd like to be able to run queries, open a specific table that I know the name of or to use the MCP server nonetheless.

## Actual Behavior
Cannot connect in any way to these large databases

## Environment
- DBCode version: 1.19.6
- VS Code (or fork) version: 1.105.1
- OS: Darwin arm64 25.0.0
- Database: MySQL
- Connection: (direct/SSH/SSL) ssh tunnel

## Error Meesages (if applicable)
```
Error getting databases for connection x, error: Query execution was interrupted, maximum statement execution time exceeded
```

## Logs
If available, paste relevant logs from the Output panel (View > Output > DBCode).
```
2025-11-27 15:09:28.809 [info] Tunnel: opened 'bastion'
2025-11-27 15:09:30.384 [info] Connection: opened 'null' on 'x' (mysql:8.0.42)
2025-11-27 15:09:57.060 [info] Connection: opened 'null' on 'x' (mysql:8.0.42)
2025-11-27 15:10:23.715 [info] Connection: opened 'null' on 'x' (mysql:8.0.42)
2025-11-27 15:10:50.649 [info] Connection: opened 'null' on 'x' (mysql:8.0.42)
2025-11-27 15:11:17.318 [info] Connection: opened 'null' on 'x' (mysql:8.0.42)
2025-11-27 15:11:43.999 [info] Connection: opened 'null' on 'x' (mysql:8.0.42)
2025-11-27 15:12:10.610 [info] Connection: opened 'null' on 'x' (mysql:8.0.42)
2025-11-27 15:12:37.141 [info] Connection: opened 'null' on 'x' (mysql:8.0.42)
2025-11-27 15:13:03.691 [info] Connection: opened 'null' on 'x' (mysql:8.0.42)
2025-11-27 15:13:52.462 [info] Connection: opened 'null' on 'x' (mysql:8.0.42)
2025-11-27 15:14:48.774 [error] Connection: 'x' failed:  SqlError: (conn:1943360, no: 1040, SQLState: 08004) Too many connections
    at Object.C.exports.createError (/Users/raphael/.cursor/extensions/dbcode.dbcode-1.19.6-universal/out/vendor/mariadb.js:5:179)
    at a.readError (/Users/raphael/.cursor/extensions/dbcode.dbcode-1.19.6-universal/out/vendor/mariadb.js:5:9902)
    at a.handshakeResult (/Users/raphael/.cursor/extensions/dbcode.dbcode-1.19.6-universal/out/vendor/mariadb.js:27:31821)
    at a.onPacketReceive (/Users/raphael/.cursor/extensions/dbcode.dbcode-1.19.6-universal/out/vendor/mariadb.js:27:29810)
    at di.receivePacketBasic (/Users/raphael/.cursor/extensions/dbcode.dbcode-1.19.6-universal/out/vendor/mariadb.js:19:330)
    at di.onData (/Users/raphael/.cursor/extensions/dbcode.dbcode-1.19.6-universal/out/vendor/mariadb.js:19:1299)
    at TLSSocket.emit (node:events:519:28)
    at TLSSocket.emit (node:domain:489:12)
    at addChunk (node:internal/streams/readable:561:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
    at TLSSocket.Readable.push (node:internal/streams/readable:392:5)
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:189:23)
    at TLSWrap.callbackTrampoline (node:internal/async_hooks:130:17)
```

**Comment by mikeburgh** [comment]
I just released 1.19.7 which should resolve this, but there are other challenges once the database load with such large tables… check out #861 which also contains some updates for this in 1.19.7

**Comment by mikeburgh** [comment]
Had to push another update, found a small issue.. try out 1.19.8

**Comment by raphael-yapla** [comment]
Thank you so much for the quick response time!

I tried 1.19.8 and I can confirm that I can connect to that large database now! Thank you!

However the introspection fails. I get the following error after a few minutes:

> "Error introspecting database db, error: Query execution was interrupted, maximum statement execution time exceeded"

```sh
2025-12-01 08:46:47.285 [info] Connection: opened 'table' on 'db' (mysql:8.0.42)
2025-12-01 08:47:12.546 [error] Connection: lightweight introspection of 'table' on 'db' error: Query execution was interrupted, maximum statement execution time exceeded
2025-12-01 08:47:13.592 [info] [Debug - 8:47:13 AM] SchemaFactory: Attempting to load schema from storage for 'table' on connection 'PnCgkgYXFqhBM0zZs8CpN'
2025-12-01 08:47:13.592 [info] [Debug - 8:47:13 AM] [STUB] Skipping createDirectory for /Users/raphael/Library/Application Support/Cursor/User/globalStorage/dbcode.dbcode (read-only mode)
2025-12-01 08:47:13.592 [info] [Debug - 8:47:13 AM] FileStore: failed to find file 'schemas/PnCgkgYXFqhBM0zZs8CpN/table.data'
2025-12-01 08:47:13.592 [info] [Debug - 8:47:13 AM] SchemaFactory: No schema found for 'table' on connection 'PnCgkgYXFqhBM0zZs8CpN'
2025-12-01 08:47:38.346 [error] Connection: introspection of 'table' on 'db' error: Query execution was interrupted, maximum statement execution time exceeded
```

We know we're an edge case scenario though and we never use the introspection queries from other tools on our production servers because we have way too many tables for it to work or be useful, we usually just query our things directly with SQL. We actually had issues in the past with these kind of queries creating performance issues on our database servers.

Would you be open to adding an option on the connections to disable introspection? Or if possible to disable the introspection on some tables based on a pattern? 99.99% of our tables are created dynamically and we're not interested in having introspections for them.

**Comment by mikeburgh** [comment]
Yeah I expected intro to fail, once you can list the databases now, you can click the icon next to them when you hover to then run queries etc.. but without introspetion it's still sub par (no auto complete, no table editing, no browsing etc).<br><br>I am open to the option to disable introspection on some tables.. and yeah maybe a name filter is the solution to apply across the board (eg filter any schema item who's name matches this pattern).. <br><br>I am also wondering if I can bump up the max execution time when running introspection just for the session, that way in theory it will just work.. <br><br>Can you run this and share the results, curious what you max_execution_time is set to now.. 

```
SELECT @@global.max_execution_time, @@session.max_execution_time;
```

Other idea I am thinking about.. at the moment the introspection is 8 or 9 queries all run in one batch.. if I break them up into single queries.. and one fails ignore the failure and work with the rest.. that gives you some introspection data at least..  Still maybe not as good an option as filtering, but for an initial connect experience it might be better (and I can alert that xx failed and put towards the filter setting on the connection to reduce things).. again still just thinking it through. <br><br>Also can you run this query, it's the column fetching, which is I am guessing where it's failing..

```
select table_name
	,column_name
	,ordinal_position
	,LOWER(data_type)
	,case when COLUMN_KEY = 'PRI' then true else false end as primaryKey
	,Case when IS_NULLABLE = 'YES' then true else false end as is_nullable 
	,case when generation_expression != '' then true else false end as is_generated
	,case when extra like '%auto_increment%' then true else false end as is_identity
	,GENERATION_EXPRESSION as generation_expression
	,case when NUMERIC_PRECISION is not null then NUMERIC_PRECISION else character_maximum_length end as length
	,numeric_scale as scale
	,case when  extra like '%auto_increment%' then extra ELSE
		case when column_default = 'NULL' then null else column_default end 
	end as column_default
	,COLUMN_COMMENT as comment
	,Case when data_type = 'enum' then  CONCAT('[', TRIM(TRAILING ')' FROM SUBSTRING(COLUMN_TYPE, 6)) , ']') else null end as column_values
FROM information_schema.columns
where table_schema = DATABASE()
ORDER BY table_name, ordinal_position;
```

I don't need the output, just the time it takes (assuming it finishes before your session execution).

**Comment by raphael-yapla** [comment]
Here's our execution time configuration, we don't want it any higher to avoid some requests spinning out of control, also because some of our backend is using lambdas limited to 30s execution time.

| Global max execution time | Session max execution time |
| :------------------------ | :------------------------- |
| 25000                     | 25000                      |

And yes you're right that introspection query does timeout on our smallest server!

My concern is that the introspection might cause some severe performance issues with our bigger server if we were to connect to it. We found that the `SHOW TABLE STATUS` queries are especially bad for us. Is that something you currently use within that introspection phase?

**Comment by mikeburgh** [comment]
Figured that was going to be the case on the columns, it's the big one.. Since this issue was opened there has been an update to break multiple queries up for MySQL (You can enable it on the config, but it given that columns one fails by itself it wont help (full introspection still expects them all to work or it fails.. and I would need to make more changes to let it accept one or more failing)<br><br>No I don't use show table status, I do use show function/procedure status, but the rest are similar to columns, getting it from the information_schema views. <br><br>I am not familiar enough with MySQL to speak to what might cause it to lock etc, and I didn't like the idea of changing execution time's automatically for users to do the introspection once I thought about.. as people who set them do so for a reason, I don't want to change it. <br><br>I am actually working through a change at the moment for databases that support schemas, to fetch single schemas only.. and do them on demand.. I think I might need to do something similar here.. if I detect a huge amount of tables, switch to on demand fetching.. it will make things like auto complete a bit of a pain.. but it's either that or have some sort of filter option up front, but that kinda sucks when you want to see something different (go back edit filter, refresh) etc..

**Comment by raphael-yapla** [comment]
I think that approach might make more sense for us yeah, like I said we're aware that we're a special case and are very used not to have all of the introspection niceties. Our main concern is that we don't want the tool to burden the database performance!

Let me know if you want us to test things for you with our setup, I'd be happy to provide feedback!

**Comment by mikeburgh** [comment]
I just released 1.26.6 which has support for progress schema loading… this will become the default eventually, but for now it need to be enabled on the connection.<br><br>If you edit the connection, at the bottom in the advanced section is now an introspection section and you can enable the progress option. <br><br>That will then show some additional options.. pre fetch will fetch the detailed information for all the tables and views when you connect (in the background) and if you disable it, then they will be fetched when you expand them individually in the tree.. and the other two options allow you to control batch size (mainly relevant for pre fetching) and how long to cache an item for once it is retrieved. <br><br>I would recommend you disable the pre fetch option, and then it will just fetch the items as you expand them in the tree.. then when you connect, it's going to run some queries to get a list of tables, procs, functions, views but only their names and basic details, that should be rather quick.. and not result in any timeouts.. basically runs: 

```
SELECT table_name, TABLE_ROWS, DATA_LENGTH as data_bytes, INDEX_LENGTH as index_bytes, table_comment as comment
FROM information_schema.tables
WHERE table_schema = DATABASE()
```

and similar for views/procs/functions. 

If that still causes timeouts, going to need to look at batching that.. which should be easy enough to do in this new approach. 

If you leave pre fetch on it will then fetch in batches when you connect, and if a batch errors it will then break that batch into individual items and do them individually.. and log to the output window any individual ones that error.. so you could still do that if you really wanted it to resolve all the tables up front, and the batch size control would let you tune how aggressive that is, but in your case it might take awhile, and probably not really meet your use case anyway.. (you do get a nice (or as nice as the VSCode api lets me) progress bar on the database in the tree when it's working through the batches fetching things). <br><br>A few notes: 

* The autocomplete at the moment will only suggest columns on tables that were either pre fetched or expanded.. I still need to wire in the language server to be able to signal that you are trying  to reference the columns on a table and hence it needs to be expanded. 
* Similar situation with diagrams, they wont include columns for tables not expanded (guessing you are not trying to diagram 300K plus tables!)
* The cached is currently not updated for an item when you perform an alter table/drop etc, but there is now a refresh option on the context menu of individual items to allow you to do a specific refresh until I get the automatic one wired up for this new approach.

I will tidy those issues up as I continue to roll this out to the other drivers, and tighten up some of the rough edges with it. <br><br>Let me know how it goes.. and if we need to go down the batching on the initial query route.

**Comment by raphael-yapla** [comment]
Thank you so much, we really appreciate your work on this!

I just gave it a try and here are my findings:

- I can connect without issues now, no more timeout on connections
- When I try to expand our main database then it timeouts and I can't list the tables
- That means I also can't use the "Open Table" command
- I can however create a new SQL file and query the database without issues, no timeout or delay there

Overall very happy with this, thanks again

<details>
<summary>Some logs if it's of any help</summary>

```sh
2026-01-12 09:16:31.644 [info] Tunnel: opened 'bastion'
2026-01-12 09:16:33.136 [info] Connection: opened 'main-db' on 'prod' (mysql:8.0.42)
2026-01-12 09:17:00.406 [error] Connection: introspection of 'main-db' on 'prod' error: Query execution was interrupted, maximum statement execution time exceeded
2026-01-12 09:18:34.125 [info] [Debug - 9:18:34 AM] SchemaFactory: Attempting to load schema from storage for 'main-db' on connection 'PnCgkgYXFqhBM0zZs8CpN'
2026-01-12 09:18:34.126 [info] [Debug - 9:18:34 AM] [STUB] Skipping createDirectory for /Users/raphael/Library/Application Support/Cursor/User/globalStorage/dbcode.dbcode (read-only mode)
2026-01-12 09:18:34.126 [info] [Debug - 9:18:34 AM] FileStore: failed to find file 'schemas/PnCgkgYXFqhBM0zZs8CpN/main-db.data'
2026-01-12 09:18:34.126 [info] [Debug - 9:18:34 AM] SchemaFactory: No schema found for 'main-db' on connection 'PnCgkgYXFqhBM0zZs8CpN'
2026-01-12 09:18:34.128 [info] No schema found for: PnCgkgYXFqhBM0zZs8CpN main-db

2026-01-12 09:18:34.129 [info] [Debug - 9:18:34 AM] SchemaFactory: Attempting to load schema from storage for 'main-db' on connection 'PnCgkgYXFqhBM0zZs8CpN'
2026-01-12 09:18:34.129 [info] [Debug - 9:18:34 AM] FileStore: failed to find file 'schemas/PnCgkgYXFqhBM0zZs8CpN/main-db.data'
2026-01-12 09:18:34.129 [info] [Debug - 9:18:34 AM] SchemaFactory: No schema found for 'main-db' on connection 'PnCgkgYXFqhBM0zZs8CpN'
2026-01-12 09:18:34.189 [info] [Debug - 9:18:34 AM] SchemaFactory: Attempting to load schema from storage for 'main-db' on connection 'PnCgkgYXFqhBM0zZs8CpN'
2026-01-12 09:18:34.189 [info] [Debug - 9:18:34 AM] FileStore: failed to find file 'schemas/PnCgkgYXFqhBM0zZs8CpN/main-db.data'
2026-01-12 09:18:34.189 [info] [Debug - 9:18:34 AM] SchemaFactory: No schema found for 'main-db' on connection 'PnCgkgYXFqhBM0zZs8CpN'
2026-01-12 09:18:34.442 [info] [Debug - 9:18:34 AM] SchemaFactory: Attempting to load schema from storage for 'main-db' on connection 'PnCgkgYXFqhBM0zZs8CpN'
2026-01-12 09:18:34.442 [info] [Debug - 9:18:34 AM] FileStore: failed to find file 'schemas/PnCgkgYXFqhBM0zZs8CpN/main-db.data'
2026-01-12 09:18:34.442 [info] [Debug - 9:18:34 AM] SchemaFactory: No schema found for 'main-db' on connection 'PnCgkgYXFqhBM0zZs8CpN'
2026-01-12 09:18:34.722 [info] [Debug - 9:18:34 AM] SchemaFactory: Attempting to load schema from storage for 'main-db' on connection 'PnCgkgYXFqhBM0zZs8CpN'
2026-01-12 09:18:34.723 [info] [Debug - 9:18:34 AM] FileStore: failed to find file 'schemas/PnCgkgYXFqhBM0zZs8CpN/main-db.data'
2026-01-12 09:18:34.723 [info] No schema found for: PnCgkgYXFqhBM0zZs8CpN main-db

2026-01-12 09:18:34.723 [info] [Debug - 9:18:34 AM] SchemaFactory: No schema found for 'main-db' on connection 'PnCgkgYXFqhBM0zZs8CpN'
2026-01-12 09:18:34.895 [info] [Debug - 9:18:34 AM] SchemaFactory: Attempting to load schema from storage for 'main-db' on connection 'PnCgkgYXFqhBM0zZs8CpN'
2026-01-12 09:18:34.895 [info] [Debug - 9:18:34 AM] FileStore: failed to find file 'schemas/PnCgkgYXFqhBM0zZs8CpN/main-db.data'
2026-01-12 09:18:34.895 [info] [Debug - 9:18:34 AM] SchemaFactory: No schema found for 'main-db' on connection 'PnCgkgYXFqhBM0zZs8CpN'
2026-01-12 09:18:35.207 [info] [Debug - 9:18:35 AM] SchemaFactory: Attempting to load schema from storage for 'main-db' on connection 'PnCgkgYXFqhBM0zZs8CpN'
2026-01-12 09:18:35.207 [info] No schema found for: PnCgkgYXFqhBM0zZs8CpN main-db

2026-01-12 09:18:35.207 [info] [Debug - 9:18:35 AM] FileStore: failed to find file 'schemas/PnCgkgYXFqhBM0zZs8CpN/main-db.data'
2026-01-12 09:18:35.207 [info] [Debug - 9:18:35 AM] SchemaFactory: No schema found for 'main-db' on connection 'PnCgkgYXFqhBM0zZs8CpN'
2026-01-12 09:18:35.374 [info] [Debug - 9:18:35 AM] SchemaFactory: Attempting to load schema from storage for 'main-db' on connection 'PnCgkgYXFqhBM0zZs8CpN'
2026-01-12 09:18:35.374 [info] [Debug - 9:18:35 AM] FileStore: failed to find file 'schemas/PnCgkgYXFqhBM0zZs8CpN/main-db.data'
2026-01-12 09:18:35.374 [info] [Debug - 9:18:35 AM] SchemaFactory: No schema found for 'main-db' on connection 'PnCgkgYXFqhBM0zZs8CpN'
2026-01-12 09:18:35.616 [info] [Debug - 9:18:35 AM] SchemaFactory: Attempting to load schema from storage for 'main-db' on connection 'PnCgkgYXFqhBM0zZs8CpN'
2026-01-12 09:18:35.616 [info] [Debug - 9:18:35 AM] FileStore: failed to find file 'schemas/PnCgkgYXFqhBM0zZs8CpN/main-db.data'
2026-01-12 09:18:35.616 [info] [Debug - 9:18:35 AM] SchemaFactory: No schema found for 'main-db' on connection 'PnCgkgYXFqhBM0zZs8CpN'
2026-01-12 09:18:35.616 [info] No schema found for: PnCgkgYXFqhBM0zZs8CpN main-db

2026-01-12 09:18:35.806 [info] [Debug - 9:18:35 AM] SchemaFactory: Attempting to load schema from storage for 'main-db' on connection 'PnCgkgYXFqhBM0zZs8CpN'
2026-01-12 09:18:35.806 [info] [Debug - 9:18:35 AM] FileStore: failed to find file 'schemas/PnCgkgYXFqhBM0zZs8CpN/main-db.data'
2026-01-12 09:18:35.806 [info] [Debug - 9:18:35 AM] SchemaFactory: No schema found for 'main-db' on connection 'PnCgkgYXFqhBM0zZs8CpN'
2026-01-12 09:18:36.433 [info] [Debug - 9:18:36 AM] SchemaFactory: Attempting to load schema from storage for 'main-db' on connection 'PnCgkgYXFqhBM0zZs8CpN'
2026-01-12 09:18:36.433 [info] [Debug - 9:18:36 AM] FileStore: failed to find file 'schemas/PnCgkgYXFqhBM0zZs8CpN/main-db.data'
2026-01-12 09:18:36.433 [info] No schema found for: PnCgkgYXFqhBM0zZs8CpN main-db

2026-01-12 09:18:36.433 [info] [Debug - 9:18:36 AM] SchemaFactory: No schema found for 'main-db' on connection 'PnCgkgYXFqhBM0zZs8CpN'
2026-01-12 09:18:36.605 [info] [Debug - 9:18:36 AM] SchemaFactory: Attempting to load schema from storage for 'main-db' on connection 'PnCgkgYXFqhBM0zZs8CpN'
2026-01-12 09:18:36.605 [info] No schema found for: PnCgkgYXFqhBM0zZs8CpN main-db

2026-01-12 09:18:36.605 [info] [Debug - 9:18:36 AM] FileStore: failed to find file 'schemas/PnCgkgYXFqhBM0zZs8CpN/main-db.data'
2026-01-12 09:18:36.605 [info] [Debug - 9:18:36 AM] SchemaFactory: No schema found for 'main-db' on connection 'PnCgkgYXFqhBM0zZs8CpN'
2026-01-12 09:18:36.809 [info] [Debug - 9:18:36 AM] SchemaFactory: Attempting to load schema from storage for 'main-db' on connection 'PnCgkgYXFqhBM0zZs8CpN'
2026-01-12 09:18:36.810 [info] [Debug - 9:18:36 AM] FileStore: failed to find file 'schemas/PnCgkgYXFqhBM0zZs8CpN/main-db.data'
2026-01-12 09:18:36.810 [info] [Debug - 9:18:36 AM] SchemaFactory: No schema found for 'main-db' on connection 'PnCgkgYXFqhBM0zZs8CpN'
2026-01-12 09:18:37.190 [info] [Debug - 9:18:37 AM] SchemaFactory: Attempting to load schema from storage for 'main-db' on connection 'PnCgkgYXFqhBM0zZs8CpN'
2026-01-12 09:18:37.191 [info] [Debug - 9:18:37 AM] FileStore: failed to find file 'schemas/PnCgkgYXFqhBM0zZs8CpN/main-db.data'
2026-01-12 09:18:37.191 [info] [Debug - 9:18:37 AM] SchemaFactory: No schema found for 'main-db' on connection 'PnCgkgYXFqhBM0zZs8CpN'
```
</details>

**Comment by mikeburgh** [comment]
Looks like it was still using the older introspection model in those logs..

Can you disconnect, check the connection configuration is set to use the new progressive option and not pre fetch is not enabled, and then enable the debug output (see:[https://dbcode.io/docs/help-support/debug](https://dbcode.io/docs/help-support/debug))  in the output section and then try and connect… it should show log lines about shallow and v3 introspection in the logs.

**Comment by raphael-yapla** [comment]
Tried again but still getting the same exact logs, here's a screenshot of the config I have for this connection:

<img width="800" height="360" alt="Image" src="https://github.com/user-attachments/assets/cfdb23af-723d-4f6a-8eab-13c64d6ded6d" />

```sh
2026-01-12 15:22:10.402 [info] Tunnel: opened 'bastion'
2026-01-12 15:22:10.410 [debug] FileStore: Read file 'certs/awsrds.crt', bytes: 165408
2026-01-12 15:22:10.410 [debug] FileStore: Parsed file 'certs/awsrds.crt', format: 'string'
2026-01-12 15:22:11.562 [debug] MySQL: executing query, length: 89
2026-01-12 15:22:11.747 [debug] MySQL: query executed successfully, result sets: 1
2026-01-12 15:22:11.747 [info] Connection: opened 'main-db' on 'prod' (mysql:8.0.42)
2026-01-12 15:22:11.748 [debug] MySQL: executing query, length: 46
2026-01-12 15:22:13.151 [debug] MySQL: query executed successfully, result sets: 1
2026-01-12 15:22:13.351 [debug] MySQL: executing query, length: 72
2026-01-12 15:22:13.539 [debug] MySQL: query executed successfully, result sets: 10
2026-01-12 15:22:13.543 [debug] Connection.getDatabases: driver.getDatabases completed in 1794ms
2026-01-12 15:22:13.543 [debug] SchemaFactory: Caching 10 databases for connection 'prod'
2026-01-12 15:22:13.543 [debug] MySQL: executing query, length: 235
2026-01-12 15:22:13.555 [debug] SchemaFactory: Persisted 10 databases for connection 'prod'
2026-01-12 15:22:13.555 [debug] Connection.getDatabases: cacheDatabases completed in 14ms
2026-01-12 15:22:13.555 [debug] Connection.getDatabases: total time 1808ms
2026-01-12 15:22:13.555 [debug] Connection: getDatabases completed in 1808ms
2026-01-12 15:22:13.555 [debug] Connection: addConnection completed in 0ms
2026-01-12 15:22:13.555 [debug] Connection: resolvePending completed in 0ms
2026-01-12 15:22:13.555 [debug] SchemaFactory: Attempting to load schema from storage for 'main-db' on connection 'prod'
2026-01-12 15:22:13.556 [debug] FileStore: failed to find file 'schemas/PnCgkgYXFqhBM0zZs8CpN/main-db.data'
2026-01-12 15:22:13.556 [debug] SchemaFactory: No schema found for 'main-db' on connection 'prod'
2026-01-12 15:22:13.556 [debug] Connection: getSchema completed in 1ms
2026-01-12 15:22:13.557 [debug] Connection: no cache for 'main-db' on 'prod', awaiting full introspection
2026-01-12 15:22:13.557 [debug] Connection: introspection of 'main-db' on 'prod' starting
2026-01-12 15:22:13.557 [debug] SchemaFactory: Attempting to load schema from storage for 'main-db' on connection 'prod'
2026-01-12 15:22:13.559 [debug] FileStore: failed to find file 'schemas/PnCgkgYXFqhBM0zZs8CpN/main-db.data'
2026-01-12 15:22:13.559 [debug] SchemaFactory: No schema found for 'main-db' on connection 'prod'
2026-01-12 15:22:13.559 [debug] SchemaFactory: running shallow introspection for 'main-db' on 'prod'
2026-01-12 15:22:13.559 [debug] MySQL: executing query, length: 449
2026-01-12 15:22:38.723 [debug] MySQL: query failed: SqlError: (conn:5751176, no: 3024, SQLState: HY000) Query execution was interrupted, maximum statement execution time exceeded
sql: SELECT s.SCHEMA_NAME, IFNULL(SUM(t.data_length + t.index_length), 0)
			FROM information_schema.schemata s
			LEFT JOIN information_schema.tables t ON (s.SCHEMA_NAME = t.table_schema)
			GROUP BY s.SCHEMA_NAME
			ORDER BY s.SCHEMA_NAME - parameters:[]
2026-01-12 15:22:38.724 [debug] SchemaFactory: Caching 10 databases for connection 'prod'
2026-01-12 15:22:38.735 [debug] SchemaFactory: Persisted 10 databases for connection 'prod'
2026-01-12 15:22:38.817 [debug] MySQL: query failed: SqlError: (conn:5751177, no: 3024, SQLState: HY000) Query execution was interrupted, maximum statement execution time exceeded
sql: SELECT table_name, TABLE_ROWS, DATA_LENGTH as data_bytes, INDEX_LENGTH as index_bytes, table_comment as comment
FROM information_schema.tables
WHERE table_schema = DATABASE()
AND table_type = 'BASE TABLE'
ORDER BY table_name;SELECT table_name as view_name
... - parameters:[]
2026-01-12 15:22:38.817 [error] Connection: introspection of 'main-db' on 'prod' error: Query execution was interrupted, maximum statement execution time exceeded
```

**Comment by mikeburgh** [comment]
Thanks! The initial query to get the table list was still attempting to get their size and bytes from the information_schema, which I am guessing still meant it took longer than your time out. <br><br>I have just released 1.26.7 which now just uses: 

```sql
SHOW FULL TABLES WHERE Table_type = 'BASE TABLE'
```

Can you give it a try and see if that gets the data before the timeout kills it… there are a few more options after this I can try, but we start sacrificing performance (breaking up tables/views into separate queries, paging etc) as we start getting multiple round trips and more filtering on the SQL side. <br><br>If it does, then the row an size information will be backfilled as you expand the tables, like it does with columns and the other data.

**Comment by fredericgboutin-yapla** [comment]
I can connect to our server and then I can open the database but when I list the tables, after a long moment, I'm getting this error,

```
2026-01-15 08:17:14.207 [error] FileStore: Failed to parse 'schemas/YDuGHPElwn8jg0BqPN2xj/MY_DATABASE.data', format: 'cbor', error: Data read, but end of buffer not reached
```

On another (less heavy instance), I can connect smoothly but I'm getting this popup which I don't see as an error, it's really just that I don't want to select a default database for my server connection, so 🤷 

<img width="334" height="71" alt="Image" src="https://github.com/user-attachments/assets/68380bba-3914-48d6-af16-56f12be82829" />

**Comment by mikeburgh** [comment]
I have fixed both those errors in 1.26.12.. but still working through the overall performance with large tables.. connecting and on demand introspeciton works fine.. but it's still laggy when you do touch a table and it has to merge that detail back in.. <br><br>A lot of that lag is generating the older schema format, since a lot of the extension still uses it.. I am working on updating those to the new format, which will remove that need to re generate it… (ERD is done, table data viewing is done).. autocomplete/diagnostics in the language server is next.

**Comment by mikeburgh** [comment]
I just released 1.28.10 which has cleaned up a lot of the rough edges around these very large tables lists.. Autocomplete now works and will resolve tables on the fly that are used in statements..<br><br>The other big performance issue was the tree, if you expanded the list VSCode struggled.. so now the list limits to 5k and you can click to load more after that.. but with so many I am not sure I see a case for browsing.. The autocomplete improvements should give you good column completion for tables (might be a slight delay the first time the table needs to be introspected, but it's a single table at a time so it's generally quick.. but not instant like it is once it's in the cache.<br><br>I am still cleaning up a few more parts and converting the remaining drivers over to the new progressive format.. and once that's done things should speed up a little more as it wont need to convert back to the old format.. but for now I am going to close this.. if you notice anymore slow downs or pain points open up a new issue.

**Comment by fredericgboutin-yapla** [comment]
You've done wonder. I just tried the new version. It initially had to delete an "old schema cache" and I got an error because of this but it could connect and eventually list the tables on our "million tables" database. I retried "from scratch" after restarting my IDE and it worked without any issues 🎉 

Thank you!

**Comment by raphael-yapla** [comment]
Thank you so much for taking the time to improve your tool for our *very* specific and problematic MySQL setup! Very much appreciated!

**Comment by mikeburgh** [comment]
No worries at all, and thanks for confirming it's working (that first time was probably using the older cache which were corrupted.. there was a bug in the CBOR module that corrupted the cache for large item counts.<br><br>If you find any other issues or parts that slow down, don't perform well.. just let me know.
